version: "3.7"

services:
  media-proxy:
    container_name: media-proxy
    image: nginx
    volumes:
      - ./media-stack.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    # ports:
    #   - 8080:80
    restart: unless-stopped
    depends_on:
      # - jackett
      - jellyfin
      - jellyseerr
      - prowlarr
      - radarr
      - sonarr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    # ports:
    #   - 8191:8191
    restart: unless-stopped

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TIMEZONE:-Etc/UTC}
  #     - AUTO_UPDATE=true #optional
  #     - RUN_OPTS= #optional
  #   volumes:
  #     - ${JACKETT_CONFIG}:/config
  #     - ${JACKETT_DOWNLOADS}:/data/downloads
  #   # ports:
  #   #   - 9117:9117
  #   restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Etc/UTC}
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_TVSHOWS}:/data/tvshows
      - ${JELLYFIN_MOVIES}:/data/movies
      - ${DOWNLOADS}:/downloads
      - ${RADARR_MOVIES}:/movies #optional
      - ${SONARR_TVSHOWS}:/tv #optional
    ports:
    #   - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=${JELLYSEERR_LOG_LEVEL:-debug}
      - TZ=${TIMEZONE:-Etc/UTC}
    # ports:
    #   - 5055:5055
    volumes:
      - ${JELLYSEERR_CONFIG}:/app/config
    restart: unless-stopped

  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   container_name: plex
  #   # network_mode: host
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TIMEZONE:-Etc/UTC}
  #     - VERSION=docker
  #     - PLEX_CLAIM= #optional
  #     - VIRTUAL_HOST=${PLEX_VIRTUAL_HOST}
  #     - VIRTUAL_PORT=${PLEX_VIRTUAL_POST:-32400}
  #   volumes:
  #     - ${PLEX_CONFIG}:/config
  #     # - ${JELLYFIN_TVSHOWS}:/tv
  #     # - ${JELLYFIN_MOVIES}:/movies
  #     - ${JELLYFIN_TVSHOWS}:/data/tvshows
  #     - ${JELLYFIN_MOVIES}:/data/movies
  #     - ${DOWNLOADS}:/downloads
  #     - ${RADARR_MOVIES}:/movies #optional
  #     - ${SONARR_TVSHOWS}:/tv #optional
  #   ports:
  #     - 32400:32400 # web UI
  #     # - 1900:1900 #bind: An attempt was made to access a socket in a way forbidden by its access permissions.
  #     # - 3005:3005
  #     - 8324:8324
  #     - 5353:5353
  #     - 32410:32410
  #     - 32412:32412
  #     - 32413:32413
  #     - 32414:32414
  #     - 32469:32469
  #   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${PROWLARR_CONFIG}:/config
    # ports:
    #   - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${RADARR_MOVIES}:/movies #optional
      - ${RADARR_MOVIES2}:/movies2 #optional
      - ${RADARR_MOVIES3}:/movies3 #optional
      # - ${RADARR_MOVIES4}:/movies4 #optional
      # - ${RADARR_MOVIES5}:/movies5 #optional
      - ${DOWNLOADS}:/downloads #optional
    # ports:
    #   - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE:-Etc/UTC}
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${SONARR_TVSHOWS}:/tv #optional
      - ${SONARR_TVSHOWS2}:/tv2 #optional
      - ${SONARR_TVSHOWS3}:/tv3 #optional
      - ${SONARR_TVSHOWS4}:/tv4 #optional
      - ${SONARR_TVSHOWS5}:/tv5 #optional
      - ${DOWNLOADS}:/downloads #optional
    # ports:
    #   - 8989:8989
    restart: unless-stopped

networks:
  default:
    name: ${PROXY_NETWORK:-proxy-network}
    external: true
